// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortener.WebApi.Data;

#nullable disable

namespace URLShortener.WebApi.Migrations
{
    [DbContext(typeof(UrlDbContext))]
    [Migration("20230310160312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URLShortener.WebApi.Data.Dtos.UrlInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortedString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UrlInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6173),
                            CreatedBy = "MSPMQP YPPYAO",
                            OriginalString = "https://mail.google.com/mail/u/0/?pli=1#inbox",
                            ShortedString = "WR0kDa",
                            UpdatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6173)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6337),
                            CreatedBy = "ZABOYZ KCNQSK",
                            OriginalString = "https://calendar.google.com/calendar/u/0/r",
                            ShortedString = "8enV2d",
                            UpdatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6337)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6351),
                            CreatedBy = "HUJKTI QOTMHS",
                            OriginalString = "https://github.com/Maximiliyano?tab=repositories",
                            ShortedString = "LaGYOb",
                            UpdatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6351)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6362),
                            CreatedBy = "HMGWWD UOSWFW",
                            OriginalString = "https://learnenglish.britishcouncil.org/",
                            ShortedString = "jHaWHe",
                            UpdatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6362)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6372),
                            CreatedBy = "FKAPUY RZOXTE",
                            OriginalString = "https://www.youtube.com/",
                            ShortedString = "vFrUTd",
                            UpdatedAt = new DateTime(2023, 3, 10, 18, 3, 12, 476, DateTimeKind.Local).AddTicks(6372)
                        });
                });

            modelBuilder.Entity("URLShortener.WebApi.Data.Dtos.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "obwupun@gmail.com",
                            Name = "FirstFVRJ SurLMGP",
                            Password = "WSFDEI34",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "qkneiph@gmail.com",
                            Name = "FirstQACR SurTDEH",
                            Password = "DHWAJW91",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "qdauoxa@gmail.com",
                            Name = "FirstLIDT SurXTYC",
                            Password = "UQYVJI8",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jotiejp@gmail.com",
                            Name = "FirstWLWZ SurCIRX",
                            Password = "WLHXCY55",
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "vjfximq@gmail.com",
                            Name = "FirstAFDM SurMGCV",
                            Password = "KODZRO78",
                            Role = "User"
                        },
                        new
                        {
                            Id = 6,
                            Email = "aagdlpz@gmail.com",
                            Name = "FirstFDPT SurTMMP",
                            Password = "LWROWV14",
                            Role = "User"
                        },
                        new
                        {
                            Id = 7,
                            Email = "bouvxod@gmail.com",
                            Name = "FirstOAGF SurCVEZ",
                            Password = "WMMENU89",
                            Role = "User"
                        },
                        new
                        {
                            Id = 8,
                            Email = "qrrpesd@gmail.com",
                            Name = "FirstGZOY SurCRKA",
                            Password = "HDMYGF15",
                            Role = "User"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ikzwdst@gmail.com",
                            Name = "FirstZTHK SurBEHS",
                            Password = "RBEZEF9",
                            Role = "User"
                        },
                        new
                        {
                            Id = 10,
                            Email = "dnzhimx@gmail.com",
                            Name = "FirstJZGR SurURTJ",
                            Password = "CDJAIO32",
                            Role = "User"
                        },
                        new
                        {
                            Id = 11,
                            Email = "wtbenti@gmail.com",
                            Name = "FirstDYNA SurRXEX",
                            Password = "ZGEBKZ6",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
