// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortener.WebApi.Data;

#nullable disable

namespace URLShortener.WebApi.Migrations
{
    [DbContext(typeof(UrlDbContext))]
    [Migration("20230310113023_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URLShortener.WebApi.Data.Dtos.AboutDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AboutInfo");
                });

            modelBuilder.Entity("URLShortener.WebApi.Data.Dtos.UrlInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortedString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UrlInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(8824),
                            CreatedBy = "TLLZLT ZWLNCG",
                            OriginalString = "https://mail.google.com/mail/u/0/?pli=1#inbox",
                            ShortedString = "WR0kDa",
                            UpdatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(8824)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9000),
                            CreatedBy = "TBASPT BNBGXN",
                            OriginalString = "https://calendar.google.com/calendar/u/0/r",
                            ShortedString = "8enV2d",
                            UpdatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9000)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9019),
                            CreatedBy = "TEWAGK HREPMD",
                            OriginalString = "https://github.com/Maximiliyano?tab=repositories",
                            ShortedString = "LaGYOb",
                            UpdatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9019)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9033),
                            CreatedBy = "ITEGAN WTNDDO",
                            OriginalString = "https://learnenglish.britishcouncil.org/",
                            ShortedString = "jHaWHe",
                            UpdatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9033)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9045),
                            CreatedBy = "UZAZXZ YTKNVC",
                            OriginalString = "https://www.youtube.com/",
                            ShortedString = "vFrUTd",
                            UpdatedAt = new DateTime(2023, 3, 10, 13, 30, 23, 863, DateTimeKind.Local).AddTicks(9045)
                        });
                });

            modelBuilder.Entity("URLShortener.WebApi.Data.Dtos.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "zvhhvqm@gmail.com",
                            Name = "FirstJRHQ SurGSPY",
                            Password = "BJVSOC37",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cciwijj@gmail.com",
                            Name = "FirstQXEX SurGKEE",
                            Password = "AUHEBL90",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "twbpulz@gmail.com",
                            Name = "FirstFPOE SurGESP",
                            Password = "YGBJCA36",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jsjvxtn@gmail.com",
                            Name = "FirstZNLE SurXECB",
                            Password = "YYBYUR74",
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mzueypm@gmail.com",
                            Name = "FirstDPEK SurLBNP",
                            Password = "JHNCWH66",
                            Role = "User"
                        },
                        new
                        {
                            Id = 6,
                            Email = "jfwlgom@gmail.com",
                            Name = "FirstMBRF SurDRAP",
                            Password = "NETSFD82",
                            Role = "User"
                        },
                        new
                        {
                            Id = 7,
                            Email = "enfbnho@gmail.com",
                            Name = "FirstFNHZ SurYVKZ",
                            Password = "NIVCXI92",
                            Role = "User"
                        },
                        new
                        {
                            Id = 8,
                            Email = "fiwstlj@gmail.com",
                            Name = "FirstIKZU SurNGGG",
                            Password = "IAOWIK99",
                            Role = "User"
                        },
                        new
                        {
                            Id = 9,
                            Email = "rkmussj@gmail.com",
                            Name = "FirstSRND SurCEBH",
                            Password = "KWHGZY46",
                            Role = "User"
                        },
                        new
                        {
                            Id = 10,
                            Email = "adkbifa@gmail.com",
                            Name = "FirstLZFP SurINPF",
                            Password = "KHTCPM90",
                            Role = "User"
                        },
                        new
                        {
                            Id = 11,
                            Email = "cxadppc@gmail.com",
                            Name = "FirstEFPG SurODFB",
                            Password = "TOABLS33",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
